stack-tutorials/flask-setup/app/forms/users.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField
from wtforms.validators import DataRequired


class UserLoginForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = StringField('password', validators=[DataRequired()])
    remember = BooleanField('remember', validators=[DataRequired()])

stack-tutorials/flask-setup/app/__init__.py
from .webapp import get_app

stack-tutorials/flask-setup/app/blueprints/users.py
from flask import Blueprint, render_template, abort, redirect
from jinja2 import TemplateNotFound

import auth
from ..forms.users import UserLoginForm

users_bp = Blueprint('users', __name__, template_folder='templates')

@users_bp.route('/')
def users_index():
    try:
        return render_template(f'pages/users/index.html')
    except TemplateNotFound:
        abort(404)


@auth.login_forbidden
@users_bp.route('/signin', methods=['GET', 'POST'])
def users_signin():
    form = UserLoginForm()

    if form.validate_on_submit():
        user = auth.validate_user(form.username.data, form.password.data)

        if user:
            auth.signin(user)

            return redirect('/')
        else:
            form.username.errors.append("Incorrect username or password!")
    return render_template('pages/users/signin.html', form=form)


@auth.login_required
@users_bp.route('/signout', methods=['GET'])
def users_signout():
    auth.signout()

    return redirect('/')

stack-tutorials/flask-setup/app/cfg/__init__.py
from .dbcfg import DatabaseSettings, get_db_cfg
from .flaskcfg import FlaskSettings, get_flask_cfg

stack-tutorials/flask-setup/app/dal/__init__.py
from .ctx import get_engine, get_session

from .entities.user import User
from .repositories.users import UserRepository

stack-tutorials/flask-setup/app/dal/seeding/__init__.py
import random

from sqlalchemy.orm import Session

from .utils import schema_exists
from .users import seed_users


def seed_all(session: Session):
    random.seed(0)

    seed_users(session)

stack-tutorials/flask-setup/app/logs/__init__.py
import logging

logger = logging.getLogger(__name__)

stack-tutorials/flask-setup/app/templates/pages/users/index.html
{% if current_user and current_user.is_authenticated %}
  <b>Hello, {{ current_user.username }}!</b>
  <a href="{{url_for('users.users_signout')}}">Sign Out</a>
{% else %}
  <a href="{{url_for('users.users_signin')}}">Sign In</a>
{% endif %}

stack-tutorials/flask-setup/app/templates/pages/users/signin.html
<div>
  <form method="post">
    {{ form.csrf_token }}

    {% if form.username.errors %}
        <ul class="errors">
        {% for error in form.username.errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {{ form.username.label }} {{ form.username(size=20) }}
    <br/>

    {% if form.password.errors %}
        <ul class="errors">
        {% for error in form.password.errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {{ form.password.label }} {{ form.password(size=20) }}
    <br/>

    {{ form.remember.label }} {{ form.remember() }}

    <button type="submit">Sign In</button>
  </form>
</div>